import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// Font files 
// const myFont = localFont({
//   src: '../../public/fonts/nexaText.zip',
//   display: 'swap',
// })

export const metadata: Metadata = {
  title: 'Frequency invest',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
