import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import nexaText from './fonts/nexaText'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Frequency invest',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nexaText.className}>{children}</body>
    </html>
  )
}
